### PR TITLE
add editor button functionality

### PR DESCRIPTION
**Pull request by CeoFred**
The editor buttons needs some juice and i provided one, button functionality depends on browser.. Main file is in assets/js/te.js ... so many other features you can activate, but be sure it is supported by major browsers before activating.

### CODE REVIEW

**Comment by theboringdude** [comment]
@CeoFred which other functionalities are not active?

**Comment by CeoFred** [comment]
Every button present works... It all depends on the browser you use, for me I disabled some buttons from showing because they don't work well on my browser... You should visit te.js to tweak the configurations.. Very easy

**Comment by codeekage** [comment]
Can share a git demo of it working?

**Comment by CeoFred** [comment]
You should then clone my forked repo
that's the only way for now
github.com/CeoFred/ziki 

Or you just merge and test 
You gonna like it 
Works like magic with a nice browser

**Comment by theboringdude** [comment]
I will check it out now.

**Comment by CeoFred** [comment]
Would be on this side waiting for feedback..

**Pull request closed without merging**
