### PR TITLE
Header & Footer files

### PR DESCRIPTION
**Pull request by JonathanJude**
Header & Footer files..
Header contains <head> ... </head> with unique pageTitle and currently select theme

### CODE REVIEW

**Comment by JonathanJude** [comment]
see index.php for use.

**Comment by MyloCarson** [comment]
Hi Jerry, this PR should request to merge with FE branch, not ft-backend-dev. It looks like you made only Frontend changes, not Backend. Correct me if I am wrong.

**Comment by MyloCarson** [comment]
> Hi Jerry, this PR should request to merge with FE branch, not ft-backend-dev. It looks like you made only Frontend changes, not Backend. Correct me if I am wrong.

Can you kindly re-create a new PR to merge with FE branch? Thanks

**Comment by JonathanJude** [comment]
The task was to have header.php & footer.php ready, with header.php having current theme and including functions.php to be used across. Not really FE, I only used index.php as no proper structure for switching themes yet.

**Comment by MyloCarson** [comment]
> The task was to have header.php & footer.php ready, with header.php having current theme and including functions.php to be used across. Not really FE, I only used index.php as no proper structure for switching themes yet.

Footer and Header are apparently front-end related. Kindly help create a new PR to merge with FE.

**Pull request closed without merging**
